// <auto-generated />
using System;
using ChatView.Models.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatView.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200328114141_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatView.Models.DataContext.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("CallOrChat");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FilePath")
                        .HasMaxLength(250);

                    b.Property<Guid?>("McustomerFromId");

                    b.Property<Guid?>("McustomerToId");

                    b.Property<bool?>("Seen");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("McustomerFromId");

                    b.HasIndex("McustomerToId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ChatView.Models.DataContext.Mcustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .HasMaxLength(60);

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Mcustomers");
                });

            modelBuilder.Entity("ChatView.Models.DataContext.Chat", b =>
                {
                    b.HasOne("ChatView.Models.DataContext.Mcustomer", "FromId")
                        .WithMany()
                        .HasForeignKey("McustomerFromId");

                    b.HasOne("ChatView.Models.DataContext.Mcustomer", "ToId")
                        .WithMany()
                        .HasForeignKey("McustomerToId");
                });
#pragma warning restore 612, 618
        }
    }
}
